# Page settings
baseurl = "tidyverts.org"
title = "tidyverts"
languageCode = "en-us"
theme = "hugo-elate-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  
  custom_css = ["css/custom.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    brand = "tidyverts"
    home = "Home"
    pkgs = "Packages"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Tidy tools for time series."

  # Packages section
  [params.pkgs]
    enable = true
    title = "Packages"

    [[params.pkgs.item]]
      name = "tsibble"
      summary = "Temporal data frames and tools"
      img = "tsibble.png"
      alt = "tsibble-hex"
      urls = [
        ["icon-social-github", "https://github.com/tidyverts/tsibble"],
        ["icon-globe", "https://tsibble.tidyverts.org"],
        ["icon-puzzle", "https://cran.r-project.org/package=tsibble"]
      ]

    [[params.pkgs.item]]
      name = "fable"
      summary = "Tidy forecasting"
      img = "fable.png"
      alt = "fable-hex"
      urls = [
        ["icon-social-github", "https://github.com/tidyverts/fable"],
        ["icon-globe", "https://fable.tidyverts.org"]
      ]

    [[params.pkgs.item]]
      name = "feasts"
      summary = "Feature extraction and statistics"
      img = "feasts.png"
      alt = "feasts-hex"
      urls = [
        ["icon-social-github", "https://github.com/tidyverts/feasts"],
        ["icon-globe", "https://feasts.tidyverts.org"]
      ]
      
  # Footer section
  [params.footer]
    enable = false
